### ISSUE TITLE
Docker: can not load config file

### ISSUE THREAD

**Issue by Yvan-Masson** [webnet-fr/database-anonymizer#20]
Hi,

I built the Docker image as described in #19. Anonymizer properly guess the DB fields it can anonymize.

When trying to anonymize it fails at reading/parsing the config file with this error:
```
In DelegatingLoader.php line 34:
                                                          
  Cannot load resource "/var/www/anonymizer/config.yml".  
                                                          

webnet-fr:anonymizer:anonymize [-U|--url URL] [-t|--type TYPE] [-H|--host HOST] [-P|--port PORT] [-d|--database DATABASE] [-u|--user USER] [-p|--password PASSWORD] [--] <config>
```

The file is 'detected' because if I specify a wrong path the error message is clearer:
```
Configuration file "non-existent-file.yml" does not exist.
```

I confirm that the file is world-readable and is YAML valid. Also, I tried with the example provided in the README (simplified, below) with exact same result. The config tried:
```
webnet_fr_database_anonymizer:
  tables:
    users:    
      fields:
        email:    
          generator: faker    
          formatter: email    
          unique: ~
```

Maybe because I built the Docker image with PHP 8.2 instead of 7.2?

Regards,
Yvan
