### ISSUE TITLE
Error when using longitude + latitude faker formatter

### ISSUE THREAD

**Issue by r-ichard** [webnet-fr/database-anonymizer#4]
When I use longitude / latitude fields since it can return negative floats so Anonymizer throw an error : 

In Anonymizer.php line 46
```
  [WebnetFr\DatabaseAnonymizer\Exception\InvalidAnonymousValueException]  
  Generated value must be null or string  
```

**Comment by sload** [comment]
Hello @r-ichard,

Could you give me more elements so that I can reproduce the error ?

**Comment by r-ichard** [comment]
Hello, 

Sure ! Here is my config file : 

```
webnet_fr_database_anonymizer:
    tables:
        project:
            fields:
                name:
                    generator: faker
                    formatter: word
                longitude:
                    generator: faker
                    formatter: longitude
                latitude:
                    generator: faker
                    formatter: latitude
                address:
                    generator: faker
                    formatter: streetAddress
                zipCode:
                    generator: faker
                    formatter: postcode
                city:
                    generator: faker
                    formatter: city
                address_typed:
                    generator: faker
                    formatter: streetAddress
```

If I dump `$anonValue` in Anonymizer on line 46  i get : 149.299745
